### ISSUE TITLE
Traceback (most recent call last):   File "/public/zs/CodeMind/DER/Synthesis/pipeline.py", line 175, in <module>     pipeline = CodeGenerationPipeline(model, data_dir, dataset, out_dir)   File "/public/zs/CodeMind/DER/Synthesis/pipeline.py", line 24, in __init__     self.include_test = self.config['include_test'] KeyError: 'include_test'

### ISSUE THREAD

**Issue by ALLISWELL8** [Intelligent-CAT-Lab/CodeMind#4]

**Comment by topgunlcs98** [comment]
Sorry for the inconvienece we have caused...Have updated the configuration files.
